exp_kwargs:
  seed: null
  base_log_dir: runs/exp_multi_domain_fix_bug_loss_mean_infer_mean
  domain: multi
  attention: False
  multi_class: False

trainer:
  class: MultiDomainTrainer
  kwargs:
    loss_type: focal
    focal_gamma: 2
    policy_type: gcn
    epochs: 1000
    lr: 1e-4
    evaluate_freq: 10
    batch_size: 512
    infer_mean_max: mean
    multi_loss: mean
    drop_num: 1
    use_lr_decay: true
    step_size: 100
    gamma: 0.96

policy:
  policy_type: gcn
  class: GCNPolicy
  kwargs:
    mean_max: mean
    emd_size: 128
    out_size: 2
    num_pivot_node_features: 69
    num_children_node_features: 69

train_data_loader:
  class: GraphDataLoader
  kwargs:
    npy_data_path: ../../../npy_data/v2/v2_data_train
    save_dir: v2_processed_data
    processed_npy_path: null
    sample_bool: False
    train_type: train
    sample_type: upsampling
    load_type: default_order
    batch_size: 512
    max_batch_size: 10240
    depth: 2
    fanin_nodes_type: remove
    normalize: False

test_data_loader:
  class: GraphDataLoader
  kwargs: 
    npy_data_path: ../../../npy_data/v2/v2_data_test
    save_dir: v2_processed_data
    processed_npy_path: null
    sample_bool: False
    train_type: test
    max_batch_size: 10240
    sample_type: upsampling
    load_type: default_order
    depth: 2
    fanin_nodes_type: remove
    normalize: False
  